In [1]:
import numpy as np

In [7]:
myList = [1,2,3]
print(myList)
type(myList)

[1, 2, 3]


list

In [9]:
arr = np.array(myList)
arr

array([1, 2, 3])

In [4]:
type(arr)

numpy.ndarray

In [10]:
#Multiply list by 2
myList * 2

[1, 2, 3, 1, 2, 3]

In [11]:
#Multiply array by 2
arr * 2

array([2, 4, 6])

In [13]:
x = np.zeros((2,3)) 
x

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
x = np.ones((2,3)) 
x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
x = np.full((2,3),0.1) 
x

array([[0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1]])

In [16]:
#generating sequence of numbers
np.arange(10,21,5)

array([10, 15, 20])

In [18]:
np.arange(1,3.1,0.5)

array([1. , 1.5, 2. , 2.5, 3. ])

In [19]:
#generating evenly distributed numbers
np.linspace(1,2,20)

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

In [25]:
#generate random numbers
a = np.random.rand(2,3)  

In [26]:
a

array([[0.94783882, 0.01652839, 0.9543858 ],
       [0.55997694, 0.68864589, 0.90140358]])

In [28]:
np.empty([2,2])

array([[1. , 1.5],
       [2. , 2.5]])

In [29]:
x

array([[0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1]])

In [30]:
#no. of dimensions
x.ndim

2

In [31]:
x.dtype

dtype('float64')

In [32]:
x.astype(int)

array([[0, 0, 0],
       [0, 0, 0]])

In [33]:
x.shape

(2, 3)

In [34]:
x = np.array([[1,2,3],[4,5,6]]) 
x

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
x.shape

(2, 3)

In [38]:
c = x.reshape(3,2)

In [39]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
#Total no. of elements
x.size

6

In [42]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
np.resize(x,(2,4))

array([[1, 2, 3, 4],
       [5, 6, 1, 2]])

In [44]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
#Memory space - 1 byte = 8 bit
x.itemsize

8

In [46]:
x.dtype

dtype('int64')

In [47]:
# Accessingg array elements
# 0 1 2 3 4 5 6
# -7 -6 -5 -4 -3 -2 -1

a = np.array([1, 2, 5, 9, 11, 6, 14]) 

In [48]:
a[2]

5

In [49]:
a[-2]

6

In [50]:
a[-7]

1

In [51]:
#range of elements
a[1:4]

array([2, 5, 9])

In [52]:
#jump values
a[1::2]

array([2, 9, 6])

In [53]:
#reverse order
a[::-1]

array([14,  6, 11,  9,  5,  2,  1])

In [54]:
#Accessing elements within a multi dimensional array
x

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
x[0,2]

3

In [56]:
x[1,1]

5

In [58]:
#all rows, column 0
x[:,0]

array([1, 4])

In [59]:
# row 0 and all columns
x[0,:]

array([1, 2, 3])

In [60]:
a = np.array([[93,  95], [84, 100], [99,  87]])

In [61]:
a

array([[ 93,  95],
       [ 84, 100],
       [ 99,  87]])

In [62]:
a[:,1]

array([ 95, 100,  87])

In [64]:
a[0:2,1]

array([ 95, 100])

In [65]:
a[:2,1]

array([ 95, 100])

In [66]:
a = np.array([10, 20, 30, 40]) 
b = np.arange(4)

In [67]:
a

array([10, 20, 30, 40])

In [68]:
b

array([0, 1, 2, 3])

In [69]:
a + b #addition

array([10, 21, 32, 43])

In [70]:
a - b #subtraction

array([10, 19, 28, 37])

In [72]:
a * b #multiplication element wise

array([  0,  20,  60, 120])

In [73]:
A = np.array([[1,1], [0,1]])
B = np.array( [[2,0], [3,4]])

In [74]:
A * B #multiplication element wise

array([[2, 0],
       [0, 4]])

In [75]:
#Matrix Multiplication
np.dot(A,B)

array([[5, 4],
       [3, 4]])

In [76]:
np.matmul(A,B)

array([[5, 4],
       [3, 4]])

In [77]:
a = np.array([10, 20, 65, 80]) 
b = np.arange(1, 5)

In [78]:
a/b #division

array([10.        , 10.        , 21.66666667, 20.        ])

In [79]:
a//b

array([10, 10, 21, 20])

In [80]:
a % b

array([0, 0, 2, 0])

In [81]:
a ** b

array([      10,      400,   274625, 40960000])

In [82]:
a

array([10, 20, 65, 80])

In [83]:
a ** 2 #square of array elements

array([ 100,  400, 4225, 6400])

In [84]:
np.sqrt(a) #square root of array elements

array([3.16227766, 4.47213595, 8.06225775, 8.94427191])

In [85]:
#conditional operation
a = np.array([10, 20, 30, 40]) 
a < [8, 10, 32, 50] 

array([False, False,  True,  True])

In [86]:
a

array([10, 20, 30, 40])

In [87]:
a.min() #get min value

10

In [88]:
a.max() #get max value

40

In [89]:
a.mean() #calculatin average

25.0

In [90]:
a.sum()

100

In [91]:
A

array([[1, 1],
       [0, 1]])

In [92]:
A.sum() #sum of all values

3

In [94]:
A.sum(axis=0) #sum axis 0

array([1, 2])

In [95]:
A.sum(axis=1) #sum axis 1

array([2, 1])